name: base_flutter_app
description: Flutter plugin for manage your app with basic and general functionalities.
version: 0.0.1
repository: https://github.com/JoseTabares/base_flutter_app

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  base_models: ^0.0.2
  base_data: ^0.0.1
  http: ^0.12.2
  sembast: ^2.4.7+6
  encrypt: ^4.0.2
  crypto: ^2.1.5
  path_provider: ^1.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sofka.base_flutter_app
        pluginClass: BaseFlutterAppPlugin
      ios:
        pluginClass: BaseFlutterAppPlugin
