name: base_flutter_app
description: Flutter plugin for manage your app with basic and general functionalities.
version: 0.0.1
repository: https://github.com/JoseTabares/base_flutter_app

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  base_models: ^2.0.0
  base_data: ^2.0.0
  http: ^0.13.3
  sembast: ^3.1.0+2
  encrypt: ^5.0.0
  crypto: ^3.0.1
  meta: ^1.3.0
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sofka.base_flutter_app
        pluginClass: BaseFlutterAppPlugin
      ios:
        pluginClass: BaseFlutterAppPlugin
